# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: push

jobs:
  test:
    env:
      COVERAGE: Y
      CC_TEST_REPORTER_ID: 9eb2d68da2519eb132eb0c3e063c4b899247c7ebe390a68c286545fc9f346286

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rspec

    - name: Upload coverage results to Code Climate
      uses: paambaati/codeclimate-action@v5.0.0

  linters:
    name: Linters
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0 # Use .ruby-version file instead of duplicating here and in Gemfile?
          bundler-cache: true

      - name: Run ruby linter
        run: bundle exec rubocop --format github
